const actionTypes = {
	SET_TODOS: "SET_TODOS",
	ADD_TODO: "ADD_TODO",
	ADD_TODOS: "ADD_TODOS",
	UPDATE_TODO: "UPDATE_TODO",
	REMOVE_TODO: "REMOVE_TODO",
	REMOVE_COMPLETED_TODOS: "REMOVE_COMPLETED_TODOS"
}

export default actionTypes