const actionTypes = {
	SET_PROJECTS: "SET_PROJECTS",
	ADD_PROJECT: "ADD_PROJECT",
	ADD_PROJECTS: "ADD_PROJECTS",
	UPDATE_PROJECT: "UPDATE_PROJECT",
	REMOVE_PROJECT: "REMOVE_PROJECT",
}

export default actionTypes